services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: expedition-service-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - IAE_NIM=102022430048
      - LIGHTHOUSE_SCHEMA_CACHE_ENABLE=false
      - LIGHTHOUSE_QUERY_CACHE_ENABLE=false
    working_dir: /var/www
    ports:
      - "8000:8000"
    networks:
      - expedition-network

networks:
  expedition-network:
    driver: bridge
