services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: expedition-service-app
    container_name: expedition-app
    restart: unless-stopped
    environment:
      - IAE_NIM=102022430048
      - LIGHTHOUSE_CACHE_ENABLE=false
      - LIGHTHOUSE_QUERY_CACHE_ENABLE=false
    working_dir: /var/www
    command: >
      sh -c "
      if [ ! -f .env ]; then cp .env.example .env; fi &&
      composer install --no-interaction &&
      php artisan key:generate &&
      touch database/database.sqlite &&
      php artisan migrate --force &&
      php artisan l5-swagger:generate &&
      php-fpm
      "
    volumes:
      - .:/var/www
    networks:
      - expedition-network

  nginx:
    image: nginx:alpine
    container_name: expedition-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - expedition-network

networks:
  expedition-network:
    driver: bridge
